/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acidrain;

import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author Administrator
 * 
 */


public class Start extends javax.swing.JFrame {

    ImageIcon icon;
    ImageIcon ID_icon;
    ImageIcon PW_icon;
    /**
     * Creates new form Start
     */
    
    public Start() {
        icon = new ImageIcon("D:\\Eclipse\\bg\\start_bg.jpg");
        ID_icon = new ImageIcon("D:\\Eclipse\\bg\\ID.png");
        PW_icon = new ImageIcon("D:\\Eclipse\\bg\\PW.png");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrame = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                // Approach 1: Dispaly image at at full size
                g.drawImage(icon.getImage(), 0, 0, null);
                // Approach 2: Scale image to size of component
                // Dimension d = getSize();
                // g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                // Approach 3: Fix the image position in the scroll pane
                // Point p = scrollPane.getViewport().getViewPosition();
                // g.drawImage(icon.getImage(), p.x, p.y, null);
                setOpaque(false); //그림을 표시하게 설정,투명하게 조절
                super.paintComponent(g);
            }
        };
        ID = new javax.swing.JFormattedTextField();
        Password = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton(new ImageIcon("D:\\Eclipse\\bg\\login.jpg"));
        Sign_up = new javax.swing.JButton(new ImageIcon("D:\\Eclipse\\bg\\signup.jpg"));
        ID_F = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {
                // Approach 1: Dispaly image at at full size
                g.drawImage(ID_icon.getImage(), 0, 0, null);
                // Approach 2: Scale image to size of component
                // Dimension d = getSize();
                // g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                // Approach 3: Fix the image position in the scroll pane
                // Point p = scrollPane.getViewport().getViewPosition();
                // g.drawImage(icon.getImage(), p.x, p.y, null);
                setOpaque(false); //그림을 표시하게 설정,투명하게 조절
                super.paintComponent(g);
            }
        };
        PW_F = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {
                // Approach 1: Dispaly image at at full size
                g.drawImage(PW_icon.getImage(), 0, 0, null);
                // Approach 2: Scale image to size of component
                // Dimension d = getSize();
                // g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                // Approach 3: Fix the image position in the scroll pane
                // Point p = scrollPane.getViewport().getViewPosition();
                // g.drawImage(icon.getImage(), p.x, p.y, null);
                setOpaque(false); //그림을 표시하게 설정,투명하게 조절
                super.paintComponent(g);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        MainFrame.setPreferredSize(new java.awt.Dimension(600, 400));
        MainFrame.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MainFrameComponentAdded(evt);
            }
        });
        MainFrame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MainFrameComponentShown(evt);
            }
        });
        MainFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MainFrameKeyPressed(evt);
            }
        });

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDKeyPressed(evt);
            }
        });

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        Login.setMaximumSize(new java.awt.Dimension(81, 29));
        Login.setMinimumSize(new java.awt.Dimension(81, 29));
        Login.setPreferredSize(new java.awt.Dimension(81, 29));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        Sign_up.setToolTipText("");
        Sign_up.setMaximumSize(new java.awt.Dimension(81, 29));
        Sign_up.setMinimumSize(new java.awt.Dimension(81, 29));
        Sign_up.setPreferredSize(new java.awt.Dimension(81, 29));
        Sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_upMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ID_FLayout = new javax.swing.GroupLayout(ID_F);
        ID_F.setLayout(ID_FLayout);
        ID_FLayout.setHorizontalGroup(
            ID_FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        ID_FLayout.setVerticalGroup(
            ID_FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PW_FLayout = new javax.swing.GroupLayout(PW_F);
        PW_F.setLayout(PW_FLayout);
        PW_FLayout.setHorizontalGroup(
            PW_FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        PW_FLayout.setVerticalGroup(
            PW_FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainFrameLayout = new javax.swing.GroupLayout(MainFrame);
        MainFrame.setLayout(MainFrameLayout);
        MainFrameLayout.setHorizontalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainFrameLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainFrameLayout.createSequentialGroup()
                        .addComponent(ID_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainFrameLayout.createSequentialGroup()
                        .addComponent(PW_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        MainFrameLayout.setVerticalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainFrameLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addGroup(MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_F, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password)
                    .addComponent(PW_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void clearText(){
      ID.setText("");
      Password.setText("");
   }
     protected void loginCheck(String id, String pw) {
      /*
       * 로그인 체크하는 메소드
       * 연동된 DB에 있는 자료와 비교하여 체크한다.
       */
      try {
         //드라이버 로딩
         Class.forName("oracle.jdbc.driver.OracleDriver");
         String url = "jdbc:oracle:thin:@localhost:1521:orcl";
         Connection con = DriverManager.getConnection(url,"scott","root");
         Statement stat = con.createStatement();
         PreparedStatement pstmt = null;
                  
         String query, chkID;
         String test = String.valueOf(pw);
         
         int result = 0;
         Statement stmt1 = null;
         // 로그인창의 텍스트필드에 쓴값을 가져오기

         query = "SELECT * FROM MEMBERLIST"; 
         ResultSet rs1 = stat.executeQuery(query); 
         
   
         while(rs1.next()){ 
            if(id.equals(rs1.getString("ID"))){
               //System.out.println(rs1.getString(2));
               if(pw.equals(rs1.getString(2))){
                  // 아이디와 비밀번호 모두 일치하는 경우
                  result = 1;
                  clearText();
                  break;
               }else{
                  // 아이디는 일치하나 비밀번호가 잘못된 경우
                  result = 2;                  
               }
               break;
            }else{
               // 아이디부터 틀린경우
               result = 0;               
            }
         }
         if(result ==0 ){
            String infoText = "로그인 정보가 틀렸습니다.";
            JOptionPane.showMessageDialog(null, infoText, "알림창", JOptionPane.INFORMATION_MESSAGE);
         }else if(result == 2){
            String infoText = "비밀번호가 틀렸습니다.";
            JOptionPane.showMessageDialog(null, infoText, "알림창", JOptionPane.INFORMATION_MESSAGE);
         }else if(result ==1){
             dispose();
             Lobby L = new Lobby(id);
             L.setSize(1050, 800);
             Dimension frameSize = L.getSize();
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
             L.setLocation((screenSize.width - frameSize.width)/2, (screenSize.height - frameSize.height)/2);
             Container contentPane = L.getContentPane();
             L.setVisible(true);
         }
         stat.close();
         con.close();
      } catch (ClassNotFoundException | SQLException e) {
         // TODO Auto-generated catch block
         e.printStackTrace();
      }
   }
    
    
    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void Sign_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_upMouseClicked
        // 회원가입 버튼 좌클릭
        dispose();
        NewAccountFrame NewA = new NewAccountFrame();
        Dimension frameSize = NewA.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        NewA.setLocation((screenSize.width - frameSize.width)/2, (screenSize.height - frameSize.height)/2);
        Container contentPane = NewA.getContentPane();
        NewA.setVisible(true);
        
    }//GEN-LAST:event_Sign_upMouseClicked

    private void MainFrameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MainFrameComponentShown

    }//GEN-LAST:event_MainFrameComponentShown

    private void MainFrameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MainFrameComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MainFrameComponentAdded

    private void MainFrameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MainFrameKeyPressed
        // 메인화면에서 엔터키 입력시 로그인 버튼 좌클릭과 같은 행동 실행
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			//...동작을 실행한다.
            String InputID = ID.getText();
            String PW = Password.getText();
            loginCheck(InputID,PW);
        }
    }//GEN-LAST:event_MainFrameKeyPressed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        // 패스워드 입력 후 엔터키 입력시 로그인 버튼 좌클릭과 같은 행동 실행
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			//...동작을 실행한다.
            String InputID = ID.getText();
            String PW = Password.getText();
            loginCheck(InputID,PW);
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_IDKeyPressed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginKeyPressed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // 로그인 버튼 마우스 좌클릭

        String InputID = ID.getText();
        String PW = Password.getText();
        loginCheck(InputID,PW);

    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // 아이디 입력 텍스트 필드
    private javax.swing.JFormattedTextField ID;
    // ID 이미지 패널
    private javax.swing.JPanel ID_F;
    // 로그인 버튼
    private javax.swing.JButton Login;
    // 배경화면용 패널
    private javax.swing.JPanel MainFrame;
    // 패스워드 이미지 패널
    private javax.swing.JPanel PW_F;
    // 비밀번호 입력 텍스트 필드
    private javax.swing.JPasswordField Password;
    // 비밀번호 버튼
    private javax.swing.JButton Sign_up;
    // End of variables declaration//GEN-END:variables
}
